/**
 * Track8 - Tanglish quips for server-sent reminders
 *
 * Two sources, in this order:
 *   1. A local pack, always present, that needs nothing configured.
 *   2. Lines generated by an NVIDIA NIM model, refreshed in the background at
 *      most once every few hours and only when NVIDIA_NIM_API_KEY is set.
 *
 * The model is never on the path of a send. A reminder that waits for an HTTP
 * call is a reminder that arrives late, and late is the one failure this whole
 * feature exists to prevent - so `line()` reads a pool that is already in
 * memory, and the refresh happens on its own schedule and fails silently.
 *
 * These lines are generic on purpose. The server does not know who anyone is:
 * a reminder record is an endpoint, a kind, a start time and an allowance. The
 * *client* pack (js/quips.js) is where a name gets used, because that is the
 * side that has one.
 */
const LOCAL = {
  BREAK: [
    'Coffee break-nu sonninga, {n} min extra aachu. Chair unna kooptuthu.',
    'Break-la PhD panreengala? Vela wait pannuthu.',
    'Tea kadai-la kalyanam-a? {n} min over da.',
    'Meter ODI kittu iruku, aana hours count aagala. Vaanga.',
    'Stretch pannachu, scroll pannachu, {n} min-um pochu. Back to work!',
    'Break timer red-la iruku. Konjam vela-um pannalaam.'
  ],
  LUNCH: [
    'Saapadu over-a? Plate kaali, clock innum wait panudhu.',
    'Lunch {n} min over. Meals-a illa marriage sappadu-a?',
    'Food coma-la irundhu slowly wake up pannunga.',
    'Curd rice sema thaan, aana hours-um venum boss.',
    'Lunch break-a illa lunch shift-a? {n} min extra.',
    'Nalla saaptaachu. Ippo timesheet-a nalla pannalaam.'
  ]
};

const REFRESH_MS = 6 * 60 * 60 * 1000;
const MAX_GENERATED = 12;

// Kind -> generated lines. Starts empty; the local pack covers everything until
// and unless a refresh succeeds.
const generated = { BREAK: [], LUNCH: [] };
let lastRefresh = 0;
let refreshing = false;

function pool(kind) {
  const key = kind === 'LUNCH' ? 'LUNCH' : 'BREAK';
  return LOCAL[key].concat(generated[key]);
}

/**
 * A quip for a break of `kind` that is `overMinutes` past its allowance, or ''
 * unless PUSH_QUIPS=1. Server-sent reminders are plain English by default: the
 * server has no idea whether the phone at the other end found the in-app easter
 * egg, and guessing wrong means someone gets a joke they never asked for.
 */
function line(kind, overMinutes) {
  if (process.env.PUSH_QUIPS !== '1') return '';
  const lines = pool(kind);
  const pick = lines[Math.floor(Math.random() * lines.length)];
  return pick.replace(/\{n\}/g, String(Math.max(0, overMinutes)));
}

/* ------------------------------------------------------------- NIM refresh */

const NIM_URL = process.env.NVIDIA_NIM_URL || 'https://integrate.api.nvidia.com/v1/chat/completions';
const NIM_MODEL = process.env.NVIDIA_NIM_MODEL || 'meta/llama-3.1-8b-instruct';

const PROMPT = `Write ${MAX_GENERATED} short, funny reminders in Tanglish (casual Tamil written in English letters, mixed with English) nudging a software worker to end their {KIND} and get back to work.

Rules:
- One line each, under 90 characters, no numbering, no quotes, no emoji.
- Use the placeholder {n} exactly once in about half of them, where {n} is how many minutes they are over.
- Friendly and teasing, never insulting. No profanity. No names.
- Return only the lines, one per line.`;

function parseLines(text) {
  return String(text || '')
    .split('\n')
    .map((l) => l.replace(/^\s*[-*\d.)\s]+/, '').replace(/^["']|["']$/g, '').trim())
    // A model that ignores the brief produces paragraphs; a notification body
    // that long is truncated by the shade anyway, so drop rather than clip.
    .filter((l) => l.length > 8 && l.length <= 90)
    .slice(0, MAX_GENERATED);
}

async function askModel(kind) {
  const response = await fetch(NIM_URL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${process.env.NVIDIA_NIM_API_KEY}`
    },
    body: JSON.stringify({
      model: NIM_MODEL,
      temperature: 1,
      max_tokens: 700,
      messages: [{ role: 'user', content: PROMPT.replace('{KIND}', kind === 'LUNCH' ? 'lunch break' : 'coffee break') }]
    }),
    signal: AbortSignal.timeout(20000)
  });

  if (!response.ok) throw new Error(`NIM ${response.status}`);
  const data = await response.json();
  return parseLines(data.choices && data.choices[0] && data.choices[0].message.content);
}

/**
 * Top up the generated pool. Safe to call as often as you like: it is rate
 * limited by REFRESH_MS, single-flighted, and every failure leaves the previous
 * pool - or the local pack - exactly as it was.
 */
async function refresh() {
  if (!process.env.NVIDIA_NIM_API_KEY) return false;
  if (refreshing || Date.now() - lastRefresh < REFRESH_MS) return false;

  refreshing = true;
  try {
    const [breakLines, lunchLines] = await Promise.all([askModel('BREAK'), askModel('LUNCH')]);
    if (breakLines.length) generated.BREAK = breakLines;
    if (lunchLines.length) generated.LUNCH = lunchLines;
    lastRefresh = Date.now();
    console.log(`[quips] refreshed from NIM: ${generated.BREAK.length} break, ${generated.LUNCH.length} lunch`);
    return true;
  } catch (e) {
    // Deliberately quiet and non-fatal: the reminders themselves are unaffected.
    console.warn('[quips] NIM refresh failed, keeping current lines:', e.message);
    // Back off a full interval rather than retrying on every tick.
    lastRefresh = Date.now();
    return false;
  } finally {
    refreshing = false;
  }
}

module.exports = { line, refresh, parseLines, LOCAL };
